### ISSUE TITLE
Create a conceptual model representation in the form of a class diagram for the proposals

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-versioning#3]
Proposals including its parts (i.e., paragraphs) and connections

**Comment by MaxBob** [comment]
Current idea:
Paragraph's need to contain: content, history, connections.
More to come later

**Comment by MaxBob** [comment]
![para](https://cloud.githubusercontent.com/assets/10365690/7119513/f55115da-e1ba-11e4-9fe0-3003815b1109.png)

**Comment by cdparra** [comment]
I think this model will work for our first version, so we can consider this issue close.

**Comment by cdparra** [comment]
Go ahead and implement this as a first version
